### ISSUE TITLE
How to handle click and dblClick on the same element?

### ISSUE THREAD

**Issue by francoism90** [bayssmekanique/vue-click#21]
Thanks for providing this package, I really like the debounce/throttle options.

I would like to handle double click and a single click on the same element, however it triggers both of them:

```
<div
    v-click="onClick" // always triggered
    v-click.double="onDblClick" // only trigger this on dbl click
  />
```

The only workaround I think is two add to separated divs?

**Comment by nerdoza** [comment]
@francoism90, this is a known limitation. You are correct that the single click will fire on the double click action.

I could add a modifier to the directive which would allow them to work together, however, this would add a delay to the firing of the click action which might not be desirable. Would you mind giving a little context to the UX that you are intending to implement so I can understand the use case a bit better?

As an alternative, you might consider using a hold (long press) rather than a double click for the alternate action.

**Comment by francoism90** [comment]
@bayssmekanique Thanks for your reply and given details about how it works. :)

I was experimenting with a video element, like handling double click to enter fullscreen and play/pause handling.
I'm just going to stick with double click for now or switch to long press events, it seems difficult to work around it.
